#ifndef CYGNO_ROOT_DETECTOR_GEOMETRY_HH
#define CYGNO_ROOT_DETECTOR_GEOMETRY_HH

// ROOT adapter for the SAME layout used by DetectorConstruction. Positions and
// hit coordinates are millimetres. Use only with data generated by this layout;
// older 25x3 files need the matching historical analysis version.
#include "../common/DetectorGeometry.hh"
#include "TVector3.h"
#include <map>

inline void BuildDetectorMap(std::map<Int_t,TVector3>& centers)
{
  centers.clear();
  for (const auto& module : cygno::geometry::BuildModuleLayout()) {
    for (int side=0; side<2; ++side) {
      const auto center = cygno::geometry::GasCenter(module,side);
      centers[cygno::geometry::GasCopyNumber(module.id,side)] =
        TVector3(center.x,center.y,center.z);
    }
  }
}
#endif
